// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import "@/styles/globals.css";
import { Inter } from "next/font/google";
import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Maxius Landing Page",
  description: "Modern, minimalist, startup-focused landing page.",
  keywords: ["Next.js", "Maxius", "Landing Page", "Tailwind CSS"],
  metadataBase: new URL("https://maxius-landing.vercel.app"),
  openGraph: {
    title: "Maxius Landing Page",
    description: "A modern landing page inspired by Maxius.io.",
    url: "https://maxius-landing.vercel.app",
    siteName: "Maxius",
    locale: "en_US",
    type: "website",
    images: [
      {
        url: "/og-image.jpg", // dùng ảnh trong thư mục public
        width: 1200,
        height: 630,
        alt: "Maxius Landing Preview Image",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
